name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    name: Linting
    uses: sapphiredev/.github/.github/workflows/reusable-lint.yml@main

  docs:
    name: Generate Documentation
    uses: sapphiredev/.github/.github/workflows/reusable-yarn-job.yml@main
    with:
      script-name: docs

  build-and-test:
    name: Building and Testing with node v${{ matrix.node }}
    strategy:
      fail-fast: false
      matrix:
        node: [18, 19, 20, 21]
    uses: sapphiredev/.github/.github/workflows/reusable-yarn-job.yml@main
    with:
      script-name: typecheck && yarn build && yarn test
      node-version: ${{ matrix.node }}
      enable-sonar: true
    secrets:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
