name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    name: Linting
    uses: sapphiredev/.github/.github/workflows/reusable-lint.yml@main

  docs:
    name: Docgen
    if: github.event_name == 'pull_request' && false
    uses: sapphiredev/.github/.github/workflows/reusable-yarn-job.yml@main
    with:
      script-name: docs

  build:
    name: Building
    uses: sapphiredev/.github/.github/workflows/reusable-build.yml@main

  test:
    name: Tests
    uses: sapphiredev/.github/.github/workflows/reusable-tests.yml@main
    with:
      enable-sonar: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  typecheck:
    name: Typecheck
    uses: sapphiredev/.github/.github/workflows/reusable-typecheck.yml@main
