name: Documentation

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  docgen:
    uses: sapphiredev/.github/.github/workflows/reusable-docgen.yml@main
    with:
      project-name: framework
